In [1]:
import tensorflow as tf
from sklearn.datasets import load_iris
import pandas as pd 
import numpy as np

분류모델과 회귀모델의 차이점  
범주형 변수의 처리 방법인 원핫인코딩의 이유와 활성화함수 softmax를 사용하는 이유

Prepare tranning data

In [3]:
# dataset
iris = load_iris()
print(iris.keys())
print(iris.data)
print(iris.feature_names)
print(iris.target)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]

In [6]:
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

아이리스의 종속 변수는 범주형임  
종속변수가 양적이면 > 회귀  
종속변수가 범주이므로 > 분류  

In [8]:
# set Independent and Dependent Variables
iv = df_boston[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE', 'DIS','RAD','TAX','PTRATIO','B','LSTAT']]
dv = df_boston[['MEDV']]
print(iv.shape)
print(dv.shape)

(506, 13)
(506, 1)


Create a Model

In [9]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse') #모델이 학습할 방법

Tranning the Model

In [10]:
model.fit(iv,dv,epochs=10000, verbose=0)
model.fit(iv,dv,epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 3ms/step - loss: 124308.8906
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 112595.2344
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 102934.5625
Epoch 4/10
16/16 [==============================] - 0s 867us/step - loss: 93936.6797
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 85446.5938
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 77317.0234
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 69592.2422
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 62352.2461
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 55491.6680
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 49100.8398


Use Model

In [19]:
model.predict(iv[0:5])

1/1 [==============================] - 0s 18ms/step


array([[30.43663 ],
       [25.383606],
       [31.673008],
       [30.103195],
       [29.693066]], dtype=float32)

In [21]:
dv[0:5]

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [24]:
# Model function
model.get_weights()

[array([[-0.09684223],
        [ 0.04580691],
        [-0.00909957],
        [ 2.6386101 ],
        [-5.7662296 ],
        [ 4.998005  ],
        [-0.00646978],
        [-1.1480186 ],
        [ 0.22390024],
        [-0.00989422],
        [-0.60477984],
        [ 0.01333959],
        [-0.47163662]], dtype=float32),
 array([14.003501], dtype=float32)]