In [1]:
import numpy
import xarray as xr

In [2]:
file_src="./file/aaaaa.nc"
dset = xr.open_dataset(file_src)
dar = xr.Dataset(dset)

In [4]:
dset

<xarray.Dataset>
Dimensions:  (time: 2, lat: 10, lon: 10)
Coordinates:
  * time     (time) float32 9.969e+36 9.969e+36
  * lat      (lat) float32 40.0 41.0 42.0 43.0 44.0 45.0 46.0 47.0 48.0 49.0
  * lon      (lon) float32 -110.0 -109.0 -108.0 -107.0 ... -103.0 -102.0 -101.0
Data variables:
    value    (time, lat, lon) float32 ...

In [5]:
df = dset.to_dataframe()
df

value
time         lat  lon              
9.969210e+36 40.0 -110.0  87.264351
                  -109.0  52.937347
                  -108.0  38.418587
                  -107.0  55.805443
                  -106.0  92.890953
...                             ...
             49.0 -105.0   8.000000
                  -104.0   8.500000
                  -103.0   9.000000
                  -102.0   9.500000
                  -101.0  10.000000

[200 rows x 1 columns]

In [3]:
dset.variables

Frozen({'time': <xarray.IndexVariable 'time' (time: 2)>
array([9.96921e+36, 9.96921e+36], dtype=float32), 'lat': <xarray.IndexVariable 'lat' (lat: 10)>
array([40., 41., 42., 43., 44., 45., 46., 47., 48., 49.], dtype=float32), 'lon': <xarray.IndexVariable 'lon' (lon: 10)>
array([-110., -109., -108., -107., -106., -105., -104., -103., -102., -101.],
      dtype=float32), 'value': <xarray.Variable (time: 2, lat: 10, lon: 10)>
[200 values with dtype=float32]
Attributes:
    units:    Unknown})