In [2]:
import numpy as np

In [14]:
# 1차원 데이터 
array1 = np.array([1,2,3,])
print("type: ", type(array1))
print("shape: ", array1.shape)
print("dimension: ", array1.ndim)
print("dimension: ", array1.dtype)
array1

type:  <class 'numpy.ndarray'>
shape:  (3,)
dimension:  1
dimension:  int64


array([1, 2, 3])

In [13]:
# 2차원데이터, 1개의 로우와 3개의 컬럼
array3 = np.array([[1,2,3]])
print("type: ", type(array3))
print("shape: ", array3.shape)
print("dimension: ", array3.ndim)
print("dimension: ", array3.dtype)
array3

type:  <class 'numpy.ndarray'>
shape:  (1, 3)
dimension:  2
dimension:  int64


array([[1, 2, 3]])

In [12]:
# 2차원데이터, 2개의 로우와 3개의 컬럼 6개의 데이터
array2 = np.array([[1,2,3],[2,3,4,]])
print("type: ", type(array2))
print("shape: ", array2.shape)
print("dimension: ", array2.ndim)
array2

type:  <class 'numpy.ndarray'>
shape:  (2, 3)
dimension:  2


array([[1, 2, 3],
       [2, 3, 4]])

# List to ndarray  
ndarray는 같은 형태의 데이터 타입을 한개의 객채에 가질 수 있다.  

In [15]:
list1 = [1,2,3]
print(type(list1))
list2ndarray = np.array(list1)
print(list2ndarray, list2ndarray.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [16]:
list2 = [1,2,'test']
list2ndarray2 = np.array(list2)
print(list2ndarray2, list2ndarray2.dtype)


['1' '2' 'test'] <U21


In [ ]:
list2 = [1,2,3.0]
list2ndarray2 = np.array(list2)
print(list2ndarray2, list2ndarray2.dtype)

# ndarray 생성  
arrange, zeros, ones  

In [5]:
sqence_array = np.arange(105)
sqence_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104])

In [7]:
zero_array = np.zeros((3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [8]:
one_array = np.ones((3,2), dtype='int32')
one_array

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

# reshape

In [19]:
array1 = np.arange(10)
print(array1)
print(array1.reshape(2,5), array1.shape)
print(array1.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]] (10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
array2 = np.arange(12)
array2
print(array2.reshape(-1,4), array2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (12,)


In [29]:
array3 = np.arange(12)
array3
print(array3.reshape(3,-1), array2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (12,)


In [31]:
# 3 dimention array
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# 3dim to 2dim
array